### ISSUE TITLE
Add nuspec for plugin to GitHub

### ISSUE THREAD

**Issue by martijn00** [HBSequence/Sequence.Plugins#1]
Could you guys add the nuspec so we can see the dependencies, and updated them with a pull request if needed?

**Comment by martijn00** [comment]
Fixed in https://github.com/HBSequence/Sequence.Plugins/pull/5

**Comment by martijn00** [comment]
Would it be possible to publish the nuget now i've updated the project and added a nuspec?

**Comment by HBSequence** [comment]
Done. Thanks for your help.
