### ISSUE TITLE
InfiniteScrollPlugin and Pull to Refresh

### ISSUE THREAD

**Issue by PhilipAnthonyMurray** [HBSequence/Sequence.Plugins#12]
Is it possible to implement a pull to refresh mechanism such as the one from [James Montemagno](http://motzcod.es/post/128274430137/pull-to-refresh-anyish-xamarinforms-view) on top of this library? 

I'm currently using MVVMCross and I'm unsure of the implementation, if it's possible.

**Comment by HBSequence** [comment]
Hi Philip. I've no plans to update the library at the moment, sorry.
