### ISSUE TITLE
NuGet package or Xamarin Component?

### ISSUE THREAD

**Issue by DavePilks** [HBSequence/Sequence.Plugins#4]
Hi 

Are there plans to have this as a NuGet package or a Xamarin Component?

**Comment by martijn00** [comment]
Fixed in https://github.com/HBSequence/Sequence.Plugins/pull/5

**Comment by HBSequence** [comment]
Available now on Nuget: https://www.nuget.org/packages/Sequence.Plugins.InfiniteScroll/
